// FILE: core/common/src/main/java/com/hereliesaz/graffitixr/common/util/ImageProcessor.kt
package com.hereliesaz.graffitixr.common.util

import android.graphics.Bitmap
import androidx.compose.ui.geometry.Offset
import org.opencv.android.Utils
import org.opencv.core.CvType
import org.opencv.core.Mat
import org.opencv.core.MatOfPoint2f
import org.opencv.core.Point
import org.opencv.core.Rect
import org.opencv.core.Scalar
import org.opencv.core.Size
import org.opencv.imgproc.Imgproc

object ImageProcessor {

    /**
     * Unwarps an image using a perspective transform based on 4 corner points.
     * Restored to the working method from early project history.
     *
     * @param bitmap The source image.
     * @param points List of 4 Offsets representing the corners in pixel coordinates.
     *               Expected order: TL, TR, BR, BL.
     * @return The unwarped bitmap.
     */
    fun unwarpImage(bitmap: Bitmap, points: List<Offset>): Bitmap? {
        if (points.size != 4) return null

        return try {
            val src = Mat()
            Utils.bitmapToMat(bitmap, src)

            val w = bitmap.width.toDouble()
            val h = bitmap.height.toDouble()

            // Source points (already in pixel space from MainActivity)
            val srcPoints = MatOfPoint2f(
                Point(points[0].x.toDouble(), points[0].y.toDouble()),
                Point(points[1].x.toDouble(), points[1].y.toDouble()),
                Point(points[2].x.toDouble(), points[2].y.toDouble()),
                Point(points[3].x.toDouble(), points[3].y.toDouble())
            )

            // Destination points (Rectified to full original dimensions)
            val dstPoints = MatOfPoint2f(
                Point(0.0, 0.0),
                Point(w, 0.0),
                Point(w, h),
                Point(0.0, h)
            )

            val perspectiveTransform = Imgproc.getPerspectiveTransform(srcPoints, dstPoints)
            val dest = Mat()

            Imgproc.warpPerspective(src, dest, perspectiveTransform, Size(w, h))

            val resultBitmap = Bitmap.createBitmap(bitmap.width, bitmap.height, Bitmap.Config.ARGB_8888)
            Utils.matToBitmap(dest, resultBitmap)

            // Cleanup
            src.release()
            srcPoints.release()
            dstPoints.release()
            perspectiveTransform.release()
            dest.release()

            resultBitmap
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    fun removeBackground(bitmap: Bitmap): Bitmap? {
        return try {
            val rgbaMat = Mat()
            Utils.bitmapToMat(bitmap, rgbaMat)

            val bgrMat = Mat()
            Imgproc.cvtColor(rgbaMat, bgrMat, Imgproc.COLOR_RGBA2BGR)

            val bgdModel = Mat()
            val fgdModel = Mat()
            val mask = Mat(bgrMat.size(), CvType.CV_8UC1, Scalar(Imgproc.GC_BGD.toDouble()))

            // Leave a 10% margin around the edges, assume the subject is in the center
            val marginX = (bgrMat.cols() * 0.1).toInt()
            val marginY = (bgrMat.rows() * 0.1).toInt()
            val rect = Rect(marginX, marginY, bgrMat.cols() - marginX * 2, bgrMat.rows() - marginY * 2)

            // Run GrabCut algorithm
            Imgproc.grabCut(bgrMat, mask, rect, bgdModel, fgdModel, 5, Imgproc.GC_INIT_WITH_RECT)

            // Extract the foreground markers generated by GrabCut
            val prFgd = Mat(1, 1, CvType.CV_8U, Scalar(Imgproc.GC_PR_FGD.toDouble()))
            val fgd   = Mat(1, 1, CvType.CV_8U, Scalar(Imgproc.GC_FGD.toDouble()))

            val finalMask = Mat()
            org.opencv.core.Core.compare(mask, prFgd, finalMask, org.opencv.core.Core.CMP_EQ)
            val fgMask2 = Mat()
            org.opencv.core.Core.compare(mask, fgd, fgMask2, org.opencv.core.Core.CMP_EQ)
            org.opencv.core.Core.bitwise_or(finalMask, fgMask2, finalMask)

            // Apply mask to the original RGBA image to preserve transparency
            val outputMat = Mat(rgbaMat.size(), CvType.CV_8UC4, Scalar(0.0, 0.0, 0.0, 0.0))
            rgbaMat.copyTo(outputMat, finalMask)

            val outputBitmap = Bitmap.createBitmap(bitmap.width, bitmap.height, Bitmap.Config.ARGB_8888)
            Utils.matToBitmap(outputMat, outputBitmap)

            // Cleanup
            rgbaMat.release()
            bgrMat.release()
            bgdModel.release()
            fgdModel.release()
            mask.release()
            finalMask.release()
            fgMask2.release()
            prFgd.release()
            fgd.release()
            outputMat.release()

            outputBitmap
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}
