// FILE: core/common/src/main/java/com/hereliesaz/graffitixr/common/util/ImageProcessor.kt
package com.hereliesaz.graffitixr.common.util

import android.graphics.Bitmap
import androidx.compose.ui.geometry.Offset
import org.opencv.android.Utils
import org.opencv.core.CvType
import org.opencv.core.Mat
import org.opencv.core.MatOfPoint2f
import org.opencv.core.Point
import org.opencv.core.Rect
import org.opencv.core.Scalar
import org.opencv.core.Size
import org.opencv.imgproc.Imgproc

object ImageProcessor {

    /**
     * Unwarps an image using a perspective transform based on 4 corner points.
     * Restored to the working method from early project history.
     *
     * @param bitmap The source image.
     * @param points List of 4 Offsets representing the corners in pixel coordinates.
     *               Expected order: TL, TR, BR, BL.
     * @return The unwarped bitmap.
     */
    fun unwarpImage(bitmap: Bitmap, points: List<Offset>): Bitmap? {
        if (points.size != 4) return null

        return try {
            val src = Mat()
            Utils.bitmapToMat(bitmap, src)

            // Geometric Sort: Ensure TL, TR, BR, BL order
            val sortedByY = points.sortedBy { it.y }
            val topRow = sortedByY.take(2).sortedBy { it.x }
            val bottomRow = sortedByY.takeLast(2).sortedBy { it.x }

            val tl = topRow[0]
            val tr = topRow[1]
            val bl = bottomRow[0]
            val br = bottomRow[1]

            val sortedPoints = listOf(tl, tr, br, bl)

            // Source points
            val srcPoints = MatOfPoint2f(
                Point(tl.x.toDouble(), tl.y.toDouble()),
                Point(tr.x.toDouble(), tr.y.toDouble()),
                Point(br.x.toDouble(), br.y.toDouble()),
                Point(bl.x.toDouble(), bl.y.toDouble())
            )

            // Calculate ideal dimensions
            val widthA = Math.sqrt(Math.pow((br.x - bl.x).toDouble(), 2.0) + Math.pow((br.y - bl.y).toDouble(), 2.0))
            val widthB = Math.sqrt(Math.pow((tr.x - tl.x).toDouble(), 2.0) + Math.pow((tr.y - tl.y).toDouble(), 2.0))
            val maxWidth = Math.max(widthA, widthB)

            val heightA = Math.sqrt(Math.pow((tr.x - br.x).toDouble(), 2.0) + Math.pow((tr.y - br.y).toDouble(), 2.0))
            val heightB = Math.sqrt(Math.pow((tl.x - bl.x).toDouble(), 2.0) + Math.pow((tl.y - bl.y).toDouble(), 2.0))
            val maxHeight = Math.max(heightA, heightB)

            // Destination points
            val dstPoints = MatOfPoint2f(
                Point(0.0, 0.0),
                Point(maxWidth, 0.0),
                Point(maxWidth, maxHeight),
                Point(0.0, maxHeight)
            )

            val perspectiveTransform = Imgproc.getPerspectiveTransform(srcPoints, dstPoints)
            val dest = Mat()

            Imgproc.warpPerspective(src, dest, perspectiveTransform, Size(maxWidth, maxHeight))

            val resultBitmap = Bitmap.createBitmap(dest.cols(), dest.rows(), Bitmap.Config.ARGB_8888)
            Utils.matToBitmap(dest, resultBitmap)

            // Cleanup
            src.release()
            srcPoints.release()
            dstPoints.release()
            perspectiveTransform.release()
            dest.release()

            resultBitmap
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }


    fun removeBackground(bitmap: Bitmap): Bitmap? {
        return try {
            val rgbaMat = Mat()
            Utils.bitmapToMat(bitmap, rgbaMat)

            val bgrMat = Mat()
            Imgproc.cvtColor(rgbaMat, bgrMat, Imgproc.COLOR_RGBA2BGR)

            val bgdModel = Mat()
            val fgdModel = Mat()
            val mask = Mat(bgrMat.size(), CvType.CV_8UC1, Scalar(Imgproc.GC_BGD.toDouble()))

            // Leave a 10% margin around the edges, assume the subject is in the center
            val marginX = (bgrMat.cols() * 0.1).toInt()
            val marginY = (bgrMat.rows() * 0.1).toInt()
            val rect = Rect(marginX, marginY, bgrMat.cols() - marginX * 2, bgrMat.rows() - marginY * 2)

            // Run GrabCut algorithm
            Imgproc.grabCut(bgrMat, mask, rect, bgdModel, fgdModel, 5, Imgproc.GC_INIT_WITH_RECT)

            // Extract the foreground markers generated by GrabCut
            val prFgd = Mat(1, 1, CvType.CV_8U, Scalar(Imgproc.GC_PR_FGD.toDouble()))
            val fgd   = Mat(1, 1, CvType.CV_8U, Scalar(Imgproc.GC_FGD.toDouble()))

            val finalMask = Mat()
            org.opencv.core.Core.compare(mask, prFgd, finalMask, org.opencv.core.Core.CMP_EQ)
            val fgMask2 = Mat()
            org.opencv.core.Core.compare(mask, fgd, fgMask2, org.opencv.core.Core.CMP_EQ)
            org.opencv.core.Core.bitwise_or(finalMask, fgMask2, finalMask)

            // Apply mask to the original RGBA image to preserve transparency
            val outputMat = Mat(rgbaMat.size(), CvType.CV_8UC4, Scalar(0.0, 0.0, 0.0, 0.0))
            rgbaMat.copyTo(outputMat, finalMask)

            val outputBitmap = Bitmap.createBitmap(bitmap.width, bitmap.height, Bitmap.Config.ARGB_8888)
            Utils.matToBitmap(outputMat, outputBitmap)

            // Cleanup
            rgbaMat.release()
            bgrMat.release()
            bgdModel.release()
            fgdModel.release()
            mask.release()
            finalMask.release()
            fgMask2.release()
            prFgd.release()
            fgd.release()
            outputMat.release()

            outputBitmap
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}
