# Configuration for the Labeler Action

# Label 'documentation' for changes in docs/ or markdown files
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'

# Label 'feature' for changes in feature modules
feature:
  - changed-files:
      - any-glob-to-any-file:
          - 'feature/**'

# Label 'core' for changes in core modules
core:
  - changed-files:
      - any-glob-to-any-file:
          - 'core/**'

# Label 'native' for changes in C++ code
native:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/src/main/cpp/**'
          - 'core/native/**'

# Label 'build' for gradle files
build:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.gradle.kts'
          - '**/*.gradle'
          - 'buildSrc/**'
