import xml.etree.ElementTree as ET
import os

translations = {
    "GraffitiXR": "GraffitiXR",
    "Modes": "Módok",
    "Switch between AR Projection, Overlay, Mockup, and Trace modes.": "Váltás az AR Vetítés, Rétegzés, Makett és Rajzolás módok között.",
    "AR": "AR",
    "Project your artwork onto a real wall using augmented reality. Scan the wall first to place the anchor, then add your design layers.": "Vetítsd a művedet egy valódi falra a kiterjesztett valóság segítségével. Először szkenneld be a falat a horgony elhelyezéséhez, majd add hozzá a tervezési rétegeket.",
    "Overlay": "Rétegzés",
    "Layer your design over the live camera feed without AR anchoring. Great for quick framing and placement checks.": "Helyezd a tervedet az élő kameraképre AR horgonyzás nélkül. Kiváló a gyors keretezéshez és elhelyezés ellenőrzéséhez.",
    "Mockup": "Makett",
    "Preview your design composited onto a photo of a wall. No camera or scanning required.": "Tekintsd meg a tervedet egy fal fotójára kompozitálva. Nincs szükség kamerára vagy szkennelésre.",
    "Trace": "Rajzolás",
    "Use your design as a light-table overlay to trace reference lines onto a physical surface.": "Használd a tervedet világítótábla rátétként, hogy referenciavonalakat rajzolj egy fizikai felületre.",
    "Lightbox": "Világítótábla",
    "Canvas": "Vászon",
    "Mural": "Falfestmény",
    "Switch between Canvas (optimized for smaller desk-scale art) and Mural (optimized for large-scale walls and Gaussian Splatting).": "Váltás a Vászon (kisebb, asztali méretű művészetre optimalizálva) és a Falfestmény (nagy méretű falakra és Gauss-splattingra optimalizálva) között.",
    "Stencil": "Sablon",
    "Generate printable multi-layer stencils from your artwork. Each layer prints as outline-only tiles sized for US Letter paper.": "Generálj nyomtatható, többrétegű sablonokat a művedből. Minden réteg csak körvonalakat tartalmazó csempeként nyomtatódik US Letter papírméretben.",
    "Target": "Célpont",
    "Create and manage AR anchor targets. Photograph painted reference marks on the wall to lock the projection in place.": "AR horgony célpontok létrehozása és kezelése. Fényképezz le festett referenciajelöléseket a falon, hogy a vetítést a helyére rögzítsd.",
    "Survey": "Felmérés",
    "Map the wall surface to improve AR tracking accuracy.": "Térképezd fel a falfelületet az AR követési pontosság javítása érdekében.",
    "Create": "Létrehozás",
    "Photograph a reference mark on the wall to create a new AR anchor. The app will track this mark to keep your projection aligned.": "Fényképezz le egy referenciajelölést a falon egy új AR horgony létrehozásához. Az alkalmazás követni fogja ezt a jelölést, hogy a vetítés egyvonalban maradjon.",
    "Refine": "Finomítás",
    "Fine-tune the position of an existing AR anchor target.": "Egy meglévő AR horgony célpont pozíciójának finomhangolása.",
    "Progress": "Folyamat",
    "Mark completed areas of your mural to track painting progress.": "Jelöld meg a falfestményed elkészült részeit a festési folyamat nyomon követéséhez.",
    "Design": "Tervezés",
    "Add and manage design layers. Each layer can be an imported image or a freehand drawing.": "Tervezési rétegek hozzáadása és kezelése. Minden réteg lehet egy importált kép vagy egy szabadkézi rajz.",
    "Open": "Megnyitás",
    "Add an image from your gallery as a new layer.": "Adj hozzá egy képet a galériádból új rétegként.",
    "Wall": "Fal",
    "Replace the background wall photo used in Mockup mode.": "Cseréld le a Makett módban használt háttérfal fotóját.",
    "Isolate": "Kizárás",
    "Automatically remove the background from this layer, leaving only the subject on a transparent background.": "Automatikusan távolítsd el a hátteret erről a rétegről, így csak a téma marad egy átlátszó háttéren.",
    "Invert": "Invertálás",
    "Create a negative of the current layer. Blacks become whites, and colors are flipped to their opposites — useful for stencil and overlay analysis.": "Hozd létre az aktuális réteg negatívját. A feketék fehérek lesznek, a színek pedig az ellentettjükre fordulnak - hasznos a sablon és a rétegzés elemzéséhez.",
    "Outline": "Körvonal",
    "Convert this layer to black line art on a transparent background — ideal for creating stencil templates.": "Alakítsd ezt a réteget fekete vonalrajzzá átlátszó háttéren - ideális sablonok létrehozásához.",
    "Adjust": "Igazítás",
    "Fine-tune brightness, contrast, saturation, and color balance for this layer.": "Finomhangold a fényerőt, kontrasztot, telítettséget és színegyensúlyt ehhez a réteghez.",
    "Color": "Szín",
    "Tint the layer colors using red, green, and blue channel sliders.": "Színezd a réteg színeit piros, zöld és kék csatornacsúszkák segítségével.",
    "Blend": "Keverés",
    "Cycle through blend modes (Normal, Multiply, Screen, Overlay…) to control how this layer composites with layers below.": "Lapozz a keverési módok között (Normál, Szorzás, Képernyő, Rétegzés...), hogy szabályozd, hogyan kompozitálódik ez a réteg az alatta lévőkkel.",
    "Settings": "Beállítások",
    "Configure handedness, AR scan mode, units, and other app preferences.": "Konfiguráld a kezességet, az AR szkennelési módot, a mértékegységeket és az alkalmazás egyéb beállításait.",
    "Project": "Projekt",
    "Manage your project: create, save, load, and export.": "Kezeld a projektedet: létrehozás, mentés, betöltés és exportálás.",
    "New": "Új",
    "Start fresh empty project. Any unsaved changes will be lost.": "Kezdj egy friss, üres projektet. Minden nem mentett változás elvész.",
    "Save": "Mentés",
    "Save the current project to your device.": "Mentsd a jelenlegi projektet az eszközödre.",
    "Load": "Betöltés",
    "Open the project library to load a previously saved project.": "Nyisd meg a projektkönyvtárat egy korábban mentett projekt betöltéséhez.",
    "Export": "Exportálás",
    "Export a flat merged image of all visible layers to your photo gallery.": "Exportálj egy lapos, egyesített képet az összes látható rétegről a fotógalériádba.",
    "Help": "Súgó",
    "Tap any button while Help is active to see what it does.": "Koppints bármelyik gombra, miközben a Súgó aktív, hogy megtudd, mit csinál.",
    "Light": "Fény",
    "Toggle the device flashlight to illuminate your wall while working in low light.": "Kapcsold be az eszköz zseblámpáját, hogy megvilágítsd a falat, miközben gyenge fényviszonyok között dolgozol.",
    "Lock": "Zárolás",
    "Lock the touchscreen to prevent accidental changes while you spray. Triple-tap anywhere to unlock.": "Zárold az érintőképernyőt, hogy megelőzd a véletlen módosításokat permetezés közben. Koppints háromszor bárhová a feloldáshoz.",
    "Paint freehand strokes on this layer. Drag up/down on the Size button to change brush diameter; drag left/right to adjust feathering (edge softness).": "Fess szabadkézi vonásokat erre a rétegre. Húzd fel/le a Méret gombot az ecset átmérőjének megváltoztatásához; húzd balra/jobbra a tollasodás (perem lágysága) beállításához.",
    "Erase parts of this layer with a round brush. Drag up/down on the Size button to change diameter; drag left/right to adjust feathering.": "Radírozd le a réteg egyes részeit egy kerek ecsettel. Húzd fel/le a Méret gombot az átmérő megváltoztatásához; húzd balra/jobbra a tollasodás beállításához.",
    "Smear and soften areas of this layer. Drag across a region to blur it.": "Kend el és lágyítsd a réteg területeit. Húzz át egy régiót a homályosításhoz.",
    "Push and warp pixels in any direction. Drag across an area to distort it — useful for adjusting proportions.": "Told és torzítsd a képpontokat bármely irányba. Húzz át egy területet annak torzításához - hasznos az arányok beállításához.",
    "Lighten specific areas by painting over them.": "Világosíts fel bizonyos területeket úgy, hogy átfested őket.",
    "Darken specific areas by painting over them.": "Sötétíts el bizonyos területeket úgy, hogy átfested őket.",
    "Drag up/down to change brush diameter. Drag left/right to adjust feathering — a wider feather gives softer, more spray-can-like edges.": "Húzd fel/le az ecset átmérőjének megváltoztatásához. Húzd balra/jobbra a tollasodás beállításához - a szélesebb toll puhább, inkább spray-szerű éleket ad.",
    "Shows the active brush color. Drag up/down to adjust lightness; drag left/right to adjust saturation. Tap to open the full color wheel.": "Megmutatja az aktív ecset színét. Húzd fel/le a világosság beállításához; húzd balra/jobbra a telítettség beállításához. Koppints a teljes színkör megnyitásához.",
    "Add a new blank transparent layer for freehand drawing.": "Adj hozzá egy új, üres átlátszó réteget a szabadkézi rajzoláshoz.",
    "Save the current AR camera pose as a keyframe. Used to correct drift and re-align the projection after moving away and returning.": "Mentsd a jelenlegi AR kamera pózt kulcsképként. A sodródás korrigálására és a vetítés újraigazítására szolgál, miután eltávolodtál és visszatértél.",
    "This layer. Tap to activate it. Open the horizontal rail to access tools. Long-press and drag to reorder.": "Ez a réteg. Koppints az aktiválásához. Nyisd meg a vízszintes sínt az eszközök eléréséhez. Nyomd hosszan és húzd az átrendezéshez.",
    "Layers": "Rétegek",
    "Choose how many stencil layers to generate: 1 (silhouette only), 2 (silhouette + highlight), or 3 (silhouette + midtone + highlight).": "Válaszd ki, hány sablonréteget szeretnél generálni: 1 (csak sziluett), 2 (sziluett + kiemelés), vagy 3 (sziluett + középtónus + kiemelés).",
    "Rebuild": "Újraépítés",
    "Re-run the stencil generation pipeline on the current source layer.": "Futtasd újra a sablongenerálási folyamatot a jelenlegi forrásrétegen.",
    "Print": "Nyomtatás",
    "Configure the real-world print size and generate a tiled PDF for US Letter paper.": "Állítsd be a valós nyomtatási méretet, és generálj egy csempézett PDF-et US Letter papírhoz.",
    "Size": "Méret",
    "Drag up/down to set the stencil's real-world width or height in centimetres. Page count updates live.": "Húzd fel/le a sablon valós szélességének vagy magasságának centiméterben történő beállításához. Az oldalszám élőben frissül.",
    "W / H": "Sz / M",
    "Tap to switch between locking the width or the height of the output.": "Koppints a kimenet szélességének vagy magasságának rögzítése közötti váltáshoz.",
    "Print PDF": "PDF Nyomtatás",
    "Generate a tiled PDF of all stencil layers ready to print and cut. Each tile includes a 3mm overlap for assembly alignment.": "Generálj egy csempézett PDF-et az összes sablonrétegről, készen a nyomtatásra és vágásra. Minden csempe 3 mm-es átfedést tartalmaz az összeszereléshez.",
    "Save PNGs": "PNG Mentése",
    "Save each stencil layer as a separate PNG image to your gallery.": "Ments minden sablonréteget külön PNG képként a galériádba.",
    "← Editor": "← Szerkesztő",
    "Return to the main editor. Your stencil layers are preserved in the session.": "Visszatérés a főszerkesztőhöz. A sablonrétegek megmaradnak a munkamenetben.",
    "Text": "Szöveg",
    "Draw": "Rajz",
    "Edit": "Szerkesztés",
    "Font": "Betűtípus",
    "Kern": "Alávágás",
    "Bold": "Félkövér",
    "Italic": "Dőlt",
    "Shadow": "Árnyék",
    "Eraser": "Radír",
    "Blur": "Homályosítás",
    "Liquify": "Cseppfolyósítás",
    "Dodge": "Világosítás",
    "Burn": "Sötétítés",
    "Pro Tip": "Profi Tipp",
    "Double tap to switch rotation axis.": "Koppints duplán a forgástengely váltásához.",
    "OK": "OK",
    "GENERATING...": "GENERÁLÁS...",
    "Press again to add a layer.": "Nyomd meg újra a réteg hozzáadásához.",
    "Rename": "Átnevezés",
    "Edit text": "Szöveg szerkesztése",
    "Copy Edits": "Szerkesztések másolása",
    "Paste Edits": "Szerkesztések beillesztése",
    "Generate Poster": "Poszter generálása",
    "Duplicate": "Kettőzés",
    "Unlink Layer": "Réteg leválasztása",
    "Link Layer": "Réteg összekapcsolása",
    "Hide Layer": "Réteg elrejtése",
    "Show Layer": "Réteg megjelenítése",
    "Flatten All": "Összes lapítása",
    "Delete": "Törlés",
    "New Project": "Új Projekt",
    "Freeze": "Fagyasztás",
    "Choose Wall Photo": "Válassz falfotót",
    "How would you like to set the background wall?": "Hogyan szeretnéd beállítani a háttérfalat?",
    "Take Photo": "Fénykép készítése",
    "Choose from Gallery": "Választás a Galériából",
    "This device doesn't support the Depth API.\nSwitch to Canvas mode in Settings.": "Ez az eszköz nem támogatja a Mélységi API-t.\nVálts Vászon módra a Beállításokban.",
    "ARCore is required": "ARCore szükséges",
    "This device does not have ARCore installed or is not supported. Install ARCore from the Play Store to use AR features.": "Ez az eszköz nem rendelkezik ARCore telepítéssel, vagy nem támogatott. Telepítsd az ARCore-t a Play Áruházból az AR funkciók használatához.",
    "Install ARCore": "ARCore telepítése",
    "Camera permission is required for AR mode.": "A kamera engedélyezése szükséges az AR módhoz.",
    "Open Settings": "Beállítások megnyitása",
    "TARGET CREATION": "CÉLPONT LÉTREHOZÁSA",
    "Tap directly on your painted reference marks on the screen. The app will immediately isolate them.": "Koppints közvetlenül a festett referenciajelölésekre a képernyőn. Az alkalmazás azonnal elszigeteli őket.",
    "Cancel": "Mégse",
    "COPIED ✓": "MÁSOLVA ✓",
    "DEPTH DIAG  (tap to copy)": "MÉLYSÉGI DIAGN. (koppints a másoláshoz)",
    "Waiting for first frame…": "Várakozás az első képkockára...",
    "Step 1: Map your surroundings": "1. lépés: Térképezd fel a környezeted",
    "Step 2: Scan the target wall": "2. lépés: Szkenneld a célfalat",
    "Is the artwork on the correct wall?": "A mű a megfelelő falon van?",
    "Looks correct": "Helyesnek tűnik",
    "Re-detect": "Újraészlelés",
    "Re-detect Wall Surface": "Falfelület újraészlelése",
    "The anchor is placed from where you stood when you captured. ARCore picks the tracked vertical surface most directly in front of that original position.\n\n1. Return to approximately where you stood during capture\n2. Slowly pan the camera across your mural wall so ARCore can register it as a flat surface\n3. Hold steady facing the artwork, then tap below\n\nThe orange border will jump to the newly detected surface.": "A horgony onnan van elhelyezve, ahol a rögzítéskor álltál. Az ARCore azt a nyomon követett függőleges felületet választja, amely a leginkább közvetlenül az eredeti pozíció előtt van.\n\n1. Térj vissza körülbelül arra a helyre, ahol a rögzítés során álltál\n2. Lassan pásztázd a kamerát a falfestményed felett, hogy az ARCore sík felületként regisztrálhassa\n3. Tartsd stabilan a műalkotással szemben, majd koppints alább\n\nA narancssárga szegély az újonnan észlelt felületre ugrik.",
    "Use This Wall": "Ezt a falat használd",
    "Scanning…": "Szkennelés…",
    "%1$d%% matched": "%1$d%% egyezik",
    "Anchor locked": "Horgony rögzítve",
    "Choose Font": "Válassz betűtípust",
    "Done": "Kész",
    "Apply": "Alkalmaz",
    "Close": "Bezár",
    "Next": "Tovább",
    "Retake": "Újrafényképezés",
    "Capture": "Rögzítés",
    "Detail": "Részlet",
    "Opacity": "Átlátszatlanság",
    "Brightness": "Fényerő",
    "Contrast": "Kontraszt",
    "Saturation": "Telítettség",
    "Red": "Piros",
    "Green": "Zöld",
    "Blue": "Kék",
    "Undo": "Visszavonás",
    "Redo": "Újra",
    "Magic Align": "Varázslatos igazítás",
    "Create a Grid to start.": "Hozz létre egy Rácsot a kezdéshez.",
    "Scan surfaces around you.": "Szkenneld a körülötted lévő felületeket.",
    "Tap a surface to place anchor.": "Koppints egy felületre a horgony elhelyezéséhez.",
    "Looking for your Grid...": "A Rácsod keresése...",
    "Ready. (%1$d pts)": "Kész. (%1$d pont)",
    "Tap 4 times to unlock": "Koppints 4-szer a feloldáshoz",
    "GraffitiXR": "GraffitiXR",
    "Project your artwork onto a real wall or a canvas using AR or a basic camera overlay. \n\nQuickly create a mockup on a photo to show how the completed work will look. \n\nOr trace an image onto paper by using your device as a lightbox.": "Vetítsd a művedet egy valódi falra vagy vászonra AR vagy egy alapvető kameraréteg segítségével. \n\nGyorsan készíts egy makettet egy fotón, hogy megmutasd, hogyan fog kinézni az elkészült munka. \n\nVagy rajzolj át egy képet papírra úgy, hogy az eszközödet világítótáblaként használod.",
    "Import": "Importálás",
    "No projects yet": "Még nincsenek projektek",
    "Tap New above to start your first mural.\n\nYou'll be taken into the editor where you can:\n  •  Add artwork from the Design menu\n  •  Switch to AR mode to project onto a real wall\n  •  Use Overlay to float your design on the live camera\n  •  Use Mockup to preview on a wall photo\n  •  Use Lightbox to trace your design onto paper": "Koppints az Új gombra fent az első falfestményed megkezdéséhez.\n\nA szerkesztőbe kerülsz, ahol a következőket teheted:\n  •  Műalkotás hozzáadása a Tervezés menüből\n  •  Válts AR módba, hogy valódi falra vetíts\n  •  Használd a Rétegzést, hogy a tervedet az élő kamerán lebegtesd\n  •  Használd a Makettet az előnézethez egy falfotón\n  •  Használd a Világítótáblát a terved papírra rajzolásához",
    "Project Thumbnail": "Projekt miniatűr",
    "Delete project %1$s": "%1$s projekt törlése",
    "Preferences": "Beállítások",
    "Dominant Hand": "Domináns Kéz",
    "Right": "Jobb",
    "Left": "Bal",
    "Depth Diagnostic Overlay": "Mélységdiagnosztikai Rátét",
    "On": "Be",
    "Off": "Ki",
    "AR Scan Mode": "AR Szkennelési Mód",
    "Point Cloud": "Pontfelhő",
    "Gaussian Splat": "Gauss-splat",
    "Show Anchor Boundary": "Horgony határának mutatása",
    "Distance Units": "Távolság mértékegysége",
    "Imperial (ft)": "Birodalmi (ft)",
    "Metric (m)": "Metrikus (m)",
    "Canvas Background": "Vászon Háttér",
    "App Information": "Alkalmazás Információ",
    "Version": "Verzió",
    "Updates": "Frissítések",
    "Check for experimental updates": "Kísérleti frissítések keresése",
    "Install Update": "Frissítés telepítése",
    "Permissions": "Engedélyek",
    "Camera Access": "Kamera hozzáférés",
    "Photo Library Access": "Fotótár hozzáférés",
    "Notifications": "Értesítések",
    "Granted": "Engedélyezve",
    "Denied": "Megtagadva",
    "Open App Settings": "Alkalmazásbeállítások megnyitása",
    "GraffitiXR © 2025": "GraffitiXR © 2025",
    "Brush Size": "Ecsetméret",
    "Project Name": "Projekt neve",
    "Target Alignment Guide": "Célpont illesztési útmutató",
    "Captured Target": "Rögzített célpont",
    "Review Extracted Target": "Kinyert célpont áttekintése",
    "Drag corners to unwarp": "Húzd a sarkokat a kiegyenesítéshez",
    "Review Extracted Markings": "Kinyert jelölések áttekintése",
    "Exclude": "Kizárás",
    "Include": "Belefoglalás",
    "Erase Marks": "Jelölések törlése",
    "Show Features": "Funkciók megjelenítése",
    "Reset": "Visszaállítás",
    "GENERATE POSTER": "POSZTER GENERÁLÁSA",
    "Select layers to include:": "Válaszd ki a belefoglalandó rétegeket:",
    "Physical Size (Width in mm):": "Fizikai méret (szélesség mm-ben):",
    "GENERATE PDF": "PDF GENERÁLÁSA",
    "Move device slowly to recover tracking": "Mozgasd lassan az eszközt a követés helyreállításához",
    "Slowly rotate 360° to map your surroundings (%1$d°)": "Lassan forogj 360°-ot a környezeted feltérképezéséhez (%1$d°)",
    "Too dark. Turn on the flashlight.": "Túl sötét. Kapcsold be a zseblámpát.",
    "Walk left and right to build map": "Sétálj balra és jobbra a térkép felépítéséhez",
    "Move closer to the wall": "Menj közelebb a falhoz",
    "Scan higher and lower": "Szkennelj magasabbra és alacsonyabbra",
    "Background Mockup": "Háttér makett",
    "Segmentation Preview": "Szegmentálási előnézet",
    "Mode Switcher: Switch between app modes. Instructions: Tap to expand, then select AR, Overlay, Mockup, or Lightbox.": "Módváltó: Váltás az alkalmazásmódok között. Utasítások: Koppints a kibontáshoz, majd válaszd ki az AR, Rétegzés, Makett vagy Világítótábla lehetőséget.",
    "AR Mode: Project design onto a wall using spatial mapping. Instructions: Scan environment until wall is detected, then tap to place the anchor.": "AR Mód: Tervezés vetítése falra térbeli térképezéssel. Utasítások: Szkenneld a környezetet, amíg a falat nem észleli, majd koppints a horgony elhelyezéséhez.",
    "Overlay Mode: Display design over live camera without spatial tracking. Instructions: Manually scale and move the design to fit your frame.": "Rétegzés Mód: Terv megjelenítése élő kamerán térbeli követés nélkül. Utasítások: Méretezd és mozgasd manuálisan a tervet, hogy illeszkedjen a kerethez.",
    "Mockup Mode: Preview design on a static photo. Instructions: Use 'Wall' to set a background image, then arrange layers on top.": "Makett Mód: A terv előnézete egy statikus fotón. Utasítások: Használd a 'Fal' lehetőséget háttérkép beállításához, majd rendezd a rétegeket felülre.",
    "Lightbox Mode: High-brightness tracing surface. Instructions: Place paper over the screen and trace. Triple-tap anywhere to exit.": "Világítótábla Mód: Nagy fényerejű rajzoló felület. Utasítások: Helyezz papírt a képernyőre és rajzolj. Koppints háromszor bárhová a kilépéshez.",
    "Target Management: Tools for AR anchors. Instructions: Tap to access tools for creating or re-aligning the mural's position.": "Célpont Kezelés: Eszközök az AR horgonyokhoz. Utasítások: Koppints a falfestmény pozíciójának létrehozásához vagy újraigazításához szükséges eszközök eléréséhez.",
    "Scan Resolution: Switch between Mural (large scale) and Canvas (small scale). Mural uses Gaussian Splats for walls; Canvas uses Point Clouds for detailed desk-scale art.": "Szkennelési Felbontás: Váltás a Falfestmény (nagy lépték) és a Vászon (kis lépték) között. A falfestmény Gauss-splatteket használ a falakhoz; a Vászon Pontfelhőket használ a részletes asztali méretű művészethez.",
    "Create Anchor: Photograph a mark on the wall to lock projection. Instructions: Point at a distinct texture and tap. The app will track this mark.": "Horgony Létrehozása: Fényképezz le egy jelölést a falon a vetítés rögzítéséhez. Utasítások: Mutass egy jellegzetes textúrára, és koppints. Az alkalmazás követni fogja ezt a jelölést.",
    "Layer Management: Add images, text, or sketches. Instructions: Tap to expand. Long-press any layer button to open its secondary menu.": "Réteg Kezelés: Képek, szöveg vagy vázlatok hozzáadása. Utasítások: Koppints a kibontáshoz. Nyomd hosszan bármelyik réteg gombot a másodlagos menü megnyitásához.",
    "Import Image: Add a sketch or reference photo. Instructions: Select an image from your gallery. It will appear as a new design layer.": "Kép Importálása: Vázlat vagy referenciafotó hozzáadása. Utasítások: Válassz egy képet a galériádból. Új tervezési rétegként fog megjelenni.",
    "New Sketch: Add a blank layer for freehand drawing. Instructions: Select the layer to reveal brush, eraser, and smudge tools.": "Új Vázlat: Üres réteg hozzáadása szabadkézi rajzoláshoz. Utasítások: Válaszd ki a réteget az ecset, a radír és a maszatolási eszközök megjelenítéséhez.",
    "Add Text: Create a typography layer. Instructions: Tap the layer's 'Edit' button to change content and formatting.": "Szöveg Hozzáadása: Hozz létre egy tipográfiai réteget. Utasítások: Koppints a réteg 'Szerkesztés' gombjára a tartalom és a formázás módosításához.",
    "Change Wall: Set background for Mockup mode. Instructions: Select a photo of the physical wall you plan to paint on.": "Fal Módosítása: Háttér beállítása Makett módhoz. Utasítások: Válassz egy fotót a fizikai falról, amelyre festeni tervezel.",
    "Project Management: Save, load, and export work. Instructions: Tap to access administrative tasks for your mural.": "Projekt Kezelés: Mentsd, töltsd be és exportáld a munkát. Utasítások: Koppints a falfestmény adminisztratív feladatainak eléréséhez.",
    "New Project: Start a fresh mural. Instructions: Tap to reset. Warning: This clears all current work. Save first!": "Új Projekt: Kezdj egy friss falfestményt. Utasítások: Koppints a visszaállításhoz. Figyelmeztetés: Ez törli az összes jelenlegi munkát. Először ments!",
    "Save Project: Store mural and AR map. Instructions: Enter a project name and tap Save to preserve your progress.": "Projekt Mentése: Tárold a falfestményt és az AR térképet. Utasítások: Add meg a projekt nevét, és koppints a Mentés gombra a haladás megőrzéséhez.",
    "Project Library: Access saved murals. Instructions: Browse the library to resume work or import shared project files.": "Projekt Könyvtár: Hozzáférés a mentett falfestményekhez. Utasítások: Böngéssz a könyvtárban a munka folytatásához vagy a megosztott projektfájlok importálásához.",
    "Export Image: Save high-res snapshot. Instructions: Renders all visible layers into a single PNG in your photo gallery.": "Kép Exportálása: Ments nagy felbontású pillanatképet. Utasítások: Az összes látható réteget egyetlen PNG formátumban jeleníti meg a fotógalériádban.",
    "App Settings: Configure preferences. Instructions: Open to adjust handedness, units, and scanning parameters.": "Alkalmazás Beállítások: Preferenciák konfigurálása. Utasítások: Nyisd meg a kezesség, az egységek és a szkennelési paraméterek beállításához.",
    "Flashlight: Toggle device LED. Instructions: Use this to illuminate dark walls for better AR tracking.": "Zseblámpa: Kapcsold be az eszköz LED-jét. Utasítások: Használd ezt sötét falak megvilágítására a jobb AR követés érdekében.",
    "Lock/Freeze: Prevent accidental changes. Instructions: In Trace mode, disables screen. In other modes, locks layer transforms.": "Zárolás/Fagyasztás: Véletlen változtatások megelőzése. Utasítások: Rajzolás módban letiltja a képernyőt. Más módokban zárolja a réteg transzformációit.",
    "Interactive Help: Explains button functions. Instructions: Tap to activate (Cyan). While active, tap any button to see its help text.": "Interaktív Súgó: Elmagyarázza a gombok funkcióit. Utasítások: Koppints az aktiváláshoz (Cián). Amíg aktív, koppints bármelyik gombra a súgószöveg megtekintéséhez.",
    "Layer '%1$s': Active mural element. Instructions: Tap to select. Drag button up/down to reorder. Transform on screen with gestures.": "'%1$s' Réteg: Aktív falfestmény elem. Utasítások: Koppints a kiválasztáshoz. Húzd a gombot fel/le az átrendezéshez. Alakítsd át a képernyőn gesztusokkal.",
    "Edit Text: Change words in typography layer. Instructions: Tap to open the keyboard and update the text content.": "Szöveg Szerkesztése: Szavak módosítása a tipográfiai rétegben. Utasítások: Koppints a billentyűzet megnyitásához és a szöveg tartalmának frissítéséhez.",
    "Brush/Text Size: Adjust scale and softness. Instructions: Drag up/down for size. Drag left/right for brush feathering.": "Ecset/Szöveg Méret: Állítsd be a léptéket és a puhaságot. Utasítások: Húzd fel/le a mérethez. Húzd balra/jobbra az ecset tollasodásához.",
    "Font Picker: Select typography style. Instructions: Tap to browse available fonts and apply them to the text layer.": "Betűtípus Választó: Válassz tipográfiai stílust. Utasítások: Koppints a rendelkezésre álló betűtípusok böngészéséhez és alkalmazásához a szövegrétegen.",
    "Color Tool: Set active color. Instructions: Drag up/down for brightness, left/right for saturation. Tap for full color wheel.": "Szín Eszköz: Aktív szín beállítása. Utasítások: Húzd fel/le a fényerőhöz, balra/jobbra a telítettséghez. Koppints a teljes színkörhöz.",
    "Text Kerning: Adjust letter spacing. Instructions: Drag left/right to tighten or loosen the text layout.": "Szöveg Alávágás: Betűközök beállítása. Utasítások: Húzd balra/jobbra a szöveg elrendezésének szűkítéséhez vagy lazításához.",
    "Bold Toggle: Thick font weight. Instructions: Tap to toggle bold styling on the active text layer.": "Félkövér Váltó: Vastag betűvastagság. Utasítások: Koppints a félkövér stílus bekapcsolásához az aktív szövegrétegen.",
    "Italic Toggle: Slanted styling. Instructions: Tap to toggle italic styling on the active text layer.": "Dőlt Váltó: Ferde stílus. Utasítások: Koppints a dőlt stílus bekapcsolásához az aktív szövegrétegen.",
    "Text Outline: Character stroke. Instructions: Tap to toggle a visible outline around the text characters.": "Szöveg Körvonal: Karakter vonás. Utasítások: Koppints egy látható körvonal bekapcsolásához a szövegkarakterek körül.",
    "Drop Shadow: Text depth. Instructions: Tap to toggle a soft shadow behind the typography for better legibility.": "Vetett Árnyék: Szövegmélység. Utasítások: Koppints egy puha árnyék bekapcsolásához a tipográfia mögött a jobb olvashatóság érdekében.",
    "Generate Stencil: Create printable templates. Instructions: Tap to begin multi-layer stencil generation for this image.": "Sablon Generálása: Nyomtatható sablonok létrehozása. Utasítások: Koppints a többrétegű sablon generálásának megkezdéséhez a képhez.",
    "Blend Mode: Composite style. Instructions: Tap to cycle through modes like Multiply, Screen, and Overlay.": "Keverési Mód: Kompozit stílus. Utasítások: Koppints a módok, például a Szorzás, a Képernyő és a Rétegzés közötti váltáshoz.",
    "Image Adjustments: Fine-tune appearance. Instructions: Tap to reveal sliders for Opacity, Brightness, Contrast, and Saturation.": "Képigazítások: Finomhangold a megjelenést. Utasítások: Koppints a csúszkák megjelenítéséhez az Átlátszatlanság, a Fényerő, a Kontraszt és a Telítettség érdekében.",
    "Invert Colors: High-contrast negative. Instructions: Tap to flip colors. Whites become black and vice-versa—useful for tracing.": "Színek Invertálása: Nagy kontrasztú negatív. Utasítások: Koppints a színek megfordításához. A fehérek feketévé válnak és fordítva – hasznos a rajzoláshoz.",
    "Color Balance: RGB channel tuning. Instructions: Tap to reveal sliders for precise Red, Green, and Blue adjustment.": "Színegyensúly: RGB csatorna hangolás. Utasítások: Koppints a csúszkák megjelenítéséhez a pontos Piros, Zöld és Kék beállításhoz.",
    "Eraser Brush: Remove layer content. Instructions: Paint on screen to erase. Use 'Size' button to adjust diameter.": "Radírecset: Távolítsd el a réteg tartalmát. Utasítások: Fess a képernyőn a törléshez. Használd a 'Méret' gombot az átmérő beállításához.",
    "Blur/Smudge Tool: Blend colors. Instructions: Paint over regions to soften edges or smudge details together.": "Homályosító/Maszatoló Eszköz: Keverd össze a színeket. Utasítások: Fess a régiókon, hogy lágyítsd a széleket, vagy maszatold össze a részleteket.",
    "Warp Tool: Reshape design. Instructions: Drag on screen to push and pull pixels—great for adjusting proportions.": "Torzító Eszköz: Terv átalakítása. Utasítások: Húzd a képernyőn a képpontok tolásához és húzásához – nagyszerű az arányok beállításához.",
    "Dodge Tool: Lighten areas. Instructions: Paint over parts of the layer to increase their luminance.": "Világosító Eszköz: Világosíts területeket. Utasítások: Fess a réteg bizonyos részeire a fénysűrűségük növeléséhez.",
    "Burn Tool: Darken areas. Instructions: Paint over parts of the layer to decrease their luminance.": "Sötétítő Eszköz: Sötétíts területeket. Utasítások: Fess a réteg bizonyos részeire a fénysűrűségük csökkentéséhez.",
    "Isolate Subject: Auto-background removal. Instructions: Tap to extract the main subject from its background using AI.": "Téma Kizárása: Automatikus háttér-eltávolítás. Utasítások: Koppints a fő téma MI segítségével történő kivonásához a hátteréből.",
    "Sketch Outline: Line art filter. Instructions: Tap to convert the photo into a black-and-white transparent outline.": "Vázlat Körvonal: Vonalrajz szűrő. Utasítások: Koppints a fotó fekete-fehér átlátszó körvonallá alakításához.",
    "Layer Help: Toggle info for these specific layer tools. Instructions: Tap to activate. Then tap any tool icon to see what it does.": "Réteg Súgó: Kapcsold be az információkat ezekhez a speciális rétegeszközökhöz. Utasítások: Koppints az aktiváláshoz. Ezután koppints bármelyik eszköz ikonra, hogy megtudd, mit csinál.",
    "ft": "ft",
    "cm": "cm",
    "m": "m",
    "AR Projection": "AR Vetítés",
    "Projects your design onto a real wall using the phone's depth sensor and spatial tracking.": "Kivetíti a tervedet egy valódi falra a telefon mélységérzékelője és a térbeli követés segítségével.",
    "Step 1: Scan": "1. lépés: Szkennelés",
    "Point at the wall and move slowly side-to-side. Coloured splats appear as the engine maps the surface. Wait until splats cover the wall area.": "Mutass a falra, és mozogj lassan oldalra. Színes splattek jelennek meg, ahogy a motor feltérképezi a felületet. Várj, amíg a splattek beborítják a falfelületet.",
    "Step 2: Tap to Place": "2. lépés: Koppints az elhelyezéshez",
    "Just tap the screen. The app photographs the wall, extracts tracking features, and locks the anchor instantly.": "Csak koppints a képernyőre. Az alkalmazás lefényképezi a falat, kinyeri a követési funkciókat, és azonnal rögzíti a horgonyt.",
    "Step 3: Add Your Artwork": "3. lépés: Add hozzá a művedet",
    "Press 'Design' to access your layer tools. Use 'Image' to import photos, 'Draw' to sketch, or 'Text' to type.": "Nyomd meg a 'Tervezés' gombot a rétegeszközök eléréséhez. Használd a 'Kép' lehetőséget fotók importálásához, a 'Rajz' lehetőséget a vázlatkészítéshez, vagy a 'Szöveg' lehetőséget a gépeléshez.",
    "Tip: Texture Matters": "Tipp: A textúra számít",
    "Blank white walls, smooth concrete, and single-colour surfaces won't track. Aim your anchor point at graffiti, rough plaster, or any distinct mark.": "Az üres fehér falak, a sima beton és az egyszínű felületek nem követhetők. Irányítsd a horgonypontot graffitire, durva vakolatra vagy bármilyen jellegzetes jelre.",
    "Live Overlay": "Élő Rétegzés",
    "Your design floats over the live camera view — no surface scanning needed.": "A terved az élő kameranézet felett lebeg - nincs szükség felületszkennelésre.",
    "Step 1: Add Your Artwork": "1. lépés: Add hozzá a művedet",
    "Press 'Design' to access layer tools. Use 'Image' to import photos, 'Draw' to sketch, or 'Text' to type.": "Nyomd meg a 'Tervezés' gombot a rétegeszközök eléréséhez. Használd a 'Kép' lehetőséget fotók importálásához, a 'Rajz' lehetőséget a vázlatkészítéshez, vagy a 'Szöveg' lehetőséget a gépeléshez.",
    "Step 2: Position It": "2. lépés: Pozicionáld",
    "Pinch to scale, drag to reposition. The overlay stays fixed to your screen — step back to see how it fits the wall.": "Csippents a méretezéshez, húzd az áthelyezéshez. A rétegzés a képernyődhöz rögzülve marad – lépj hátra, hogy lásd, hogyan illeszkedik a falhoz.",
    "Photo Mockup": "Fotó Makett",
    "Preview your design on a photo before you ever pick up a brush.": "Tekintsd meg a terved előnézetét egy fotón, mielőtt egyáltalán ecsetet fognál.",
    "Step 1: Set the Wall": "1. lépés: Állítsd be a falat",
    "Open 'Design' and tap 'Wall' to choose or take a photo of your surface. Do this first!": "Nyisd meg a 'Tervezés' menüt, és koppints a 'Fal' lehetőségre a felületed fotójának kiválasztásához vagy elkészítéséhez. Ezt tedd először!",
    "Step 2: Add Your Artwork": "2. lépés: Add hozzá a művedet",
    "Use 'Image', 'Draw', or 'Text' to add layers on top of the wall. Pinch and drag to size and position them.": "Használd a 'Kép', 'Rajz' vagy 'Szöveg' lehetőséget, hogy rétegeket adj a fal tetejére. Csippents és húzd a méretezésükhöz és pozicionálásukhoz.",
    "Lightbox Mode": "Világítótábla Mód",
    "Turns your screen into a bright lightbox for tracing your design onto paper.": "Fényes világítótáblává változtatja a képernyődet, amellyel a tervedet papírra rajzolhatod.",
    "Step 1: Open Design Menu": "1. lépés: Tervezés Menü megnyitása",
    "Tap 'Design' to access layer tools.": "Koppints a 'Tervezés' gombra a rétegeszközök eléréséhez.",
    "Step 2: Add Content": "2. lépés: Tartalom hozzáadása",
    "Use 'Image' to import photos, 'Draw' to sketch, or 'Text' to type.": "Használd a 'Kép' lehetőséget fotók importálásához, a 'Rajz' lehetőséget a vázlatkészítéshez, vagy a 'Szöveg' lehetőséget a gépeléshez.",
    "Step 3: Tracing": "3. lépés: Rajzolás",
    "Lay paper over the screen and trace. Triple-tap anywhere to exit.": "Helyezz papírt a képernyőre és rajzolj. Koppints háromszor bárhová a kilépéshez.",
    "Create Anchor": "Horgony létrehozása",
    "Locks your projection to a specific spot on the wall. Once set, the design stays in place even if you walk around.": "A vetítést a fal egy bizonyos pontjához rögzíti. Miután beállítottad, a terv a helyén marad, még akkor is, ha sétálsz.",
    "Surface Requirements": "Felületi követelmények",
    "The wall needs visible texture — graffiti, rough plaster, brick, or stickers all work well. Smooth, blank, or single-colour walls won't hold an anchor.": "A falnak látható textúrával kell rendelkeznie - graffiti, durva vakolat, tégla vagy matricák mind jól működnek. Sima, üres vagy egyszínű falak nem tartanak meg egy horgonyt.",
    "What the Blobs Mean": "Mit jelentenek a foltok",
    "After tapping, you'll briefly see green blobs. Those are the tracking keypoints the app extracted. More blobs = stronger lock.": "Koppintás után röviden zöld foltokat fogsz látni. Ezek azok a követési kulcspontok, amelyeket az alkalmazás kinyert. Több folt = erősebb rögzítés.",
    "Import Image": "Kép Importálása",
    "Add a sketch, photo, or reference from your gallery. It appears as a new layer stacked on top of the others.": "Adj hozzá egy vázlatot, fotót vagy referenciát a galériádból. Új rétegként jelenik meg, a többi tetején.",
    "Scale and Position": "Méretezés és Pozicionálás",
    "Pinch with two fingers to resize. Drag with one finger to reposition. The layer snaps to the projected wall surface in AR mode.": "Csippents két ujjal a méretezéshez. Húzd egy ujjal a pozicionáláshoz. A réteg AR módban a kivetített falfelületre illeszkedik.",
    "Lock / Freeze": "Zárolás / Fagyasztás",
    "In Lightbox (Trace) mode: disables touch so you can lay paper on the screen without accidentally moving anything.": "Világítótábla (Rajzolás) módban: letiltja az érintést, így papírt tehetsz a képernyőre anélkül, hogy véletlenül elmozdítanál valamit.",
    "In Other Modes": "Más Módokban",
    "In AR, Overlay, and Mockup modes: locks layer transforms so designs can't be accidentally moved or scaled.": "AR, Rétegzés és Makett módokban: zárolja a réteg transzformációit, így a terveket nem lehet véletlenül mozgatni vagy méretezni.",
    "Generate Stencil": "Sablon Generálása",
    "Converts your image into printable spray-paint stencils. Each stencil represents one colour layer of the design.": "Átalakítja a képedet nyomtatható festékszóró sablonokká. Minden sablon a terv egy színrétegét képviseli.",
    "How Many Layers?": "Hány réteg?",
    "A 3-colour design produces 3 stencil sheets. More colours = more sheets. Simple high-contrast images give the best results.": "Egy 3 színű terv 3 sablonlapot eredményez. Több szín = több lap. Az egyszerű, nagy kontrasztú képek adják a legjobb eredményt.",
    "Exporting": "Exportálás",
    "Each stencil exports as a PDF. Print at 100% scale (no scaling) to get accurate life-size dimensions.": "Minden sablon PDF formátumban exportálódik. Nyomtass 100%-os méretarányban (méretezés nélkül) a pontos életnagyságú méretek eléréséhez.",
    "Opacity & Brightness": "Átlátszatlanság és Fényerő",
    "Opacity controls how transparent the layer is. Brightness shifts the overall lightness — useful to match the layer to your wall's tone.": "Az átlátszatlanság szabályozza a réteg átlátszóságát. A fényerő az általános világosságot tolja el – hasznos a réteg fal tónusához való illesztéséhez.",
    "Contrast & Saturation": "Kontraszt és Telítettség",
    "Contrast separates darks from lights — great for making stencil outlines pop. Saturation controls colour intensity; drag to zero for greyscale.": "A kontraszt elválasztja a sötéteket a világosaktól - kiválóan alkalmas a sablon körvonalainak kiemelésére. A telítettség a színintenzitást szabályozza; húzd nullára a szürkeárnyalathoz.",
    "Isolate Subject": "Téma Kizárása",
    "Uses AI to automatically remove the background, leaving only the main subject of the image.": "A mesterséges intelligenciát használja a háttér automatikus eltávolítására, így csak a kép fő témája marad.",
    "Best Results": "Legjobb Eredmények",
    "Works best on photos with a clear subject against a plain or contrasting background. Complex scenes with busy backgrounds may need manual touch-ups with the eraser.": "A legjobban azokon a fotókon működik, amelyeken tiszta téma van sima vagy kontrasztos háttér előtt. A zsúfolt hátterű összetett jelenetek manuális javítást igényelhetnek a radírral."
}

def translate_file(filepath, outpath):
    tree = ET.parse(filepath)
    root = tree.getroot()

    modified = False
    for child in root:
        if child.tag == 'string' and child.text is not None:
            original_text = child.text
            # Try to match the exact string, ignoring some escape chars differences if needed
            # For simplicity, strip exact match:
            clean_text = original_text.replace("\\'", "'").replace('\\n', '\n')

            # The XML parsing might replace \n with actual newlines or keep them.
            # We'll just look up the stripped original or the text exactly.
            if original_text in translations:
                child.text = translations[original_text]
                modified = True
            elif clean_text in translations:
                child.text = translations[clean_text].replace("'", "\\'").replace('\n', '\\n')
                modified = True
            else:
                # Fallback, just try to replace what we can or leave it
                pass

    if modified:
        # Create output directory if it doesn't exist
        os.makedirs(os.path.dirname(outpath), exist_ok=True)
        # Write out
        tree.write(outpath, encoding="utf-8", xml_declaration=True)

translate_file('app/src/main/res/values/strings.xml', 'app/src/main/res/values-hu/strings.xml')
translate_file('core/design/src/main/res/values/strings.xml', 'core/design/src/main/res/values-hu/strings.xml')

print("Translation completed.")
