package com.hereliesaz.graffitixr.design.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.platform.LocalContext
import com.hereliesaz.graffitixr.design.R

@Composable
fun rememberAppStrings(): AppStrings {
    val context = LocalContext.current
    return AppStrings(
        nav = rememberNavStrings(),
        common = AppStrings.Common(
            cancel = stringResource(R.string.cancel_button),
            done = stringResource(R.string.done_button),
            apply = stringResource(R.string.apply_button),
            close = stringResource(R.string.close_button),
            next = stringResource(R.string.next_button),
            save = stringResource(R.string.save_button),
            retake = stringResource(R.string.retake_button),
            capture = stringResource(R.string.capture_button),
            generating = stringResource(R.string.generating)
        ),
        lib = AppStrings.Library(
            title = stringResource(R.string.lib_app_title),
            description = stringResource(R.string.lib_app_description),
            newProject = stringResource(R.string.lib_new_project),
            importProject = stringResource(R.string.lib_import_project),
            noProjects = stringResource(R.string.lib_no_projects),
            noProjectsHint = stringResource(R.string.lib_no_projects_hint),
            deleteProjectDesc = { name -> context.getString(R.string.lib_delete_project_desc, name) }
        ),
        settings = AppStrings.Settings(
            title = stringResource(R.string.settings_title),
            preferences = stringResource(R.string.settings_preferences_section),
            dominantHand = stringResource(R.string.settings_hand_label),
            handRight = stringResource(R.string.settings_hand_right),
            handLeft = stringResource(R.string.settings_hand_left),
            diagOverlay = stringResource(R.string.settings_diag_label),
            on = stringResource(R.string.settings_on),
            off = stringResource(R.string.settings_off),
            scanMode = stringResource(R.string.settings_scan_mode_label),
            pointCloud = stringResource(R.string.settings_scan_mode_point_cloud),
            gaussianSplat = stringResource(R.string.settings_scan_mode_gaussian_splat),
            anchorBoundary = stringResource(R.string.settings_anchor_boundary_label),
            units = stringResource(R.string.settings_units_label),
            imperial = stringResource(R.string.settings_units_imperial),
            metric = stringResource(R.string.settings_units_metric),
            canvasBg = stringResource(R.string.settings_canvas_bg_label),
            appInfo = stringResource(R.string.settings_info_section),
            version = stringResource(R.string.settings_version_label),
            updates = stringResource(R.string.settings_updates_section),
            checkUpdates = stringResource(R.string.settings_check_updates_label),
            installUpdate = stringResource(R.string.settings_install_update_label),
            permissions = stringResource(R.string.settings_permissions_section),
            cameraAccess = stringResource(R.string.settings_camera_access),
            photoAccess = stringResource(R.string.settings_photo_access),
            notifications = stringResource(R.string.settings_notifications),
            granted = stringResource(R.string.settings_granted),
            denied = stringResource(R.string.settings_denied),
            openAppSettings = stringResource(R.string.settings_open_app_settings),
            copyright = stringResource(R.string.settings_copyright)
        ),
        editor = AppStrings.Editor(
            layers = stringResource(R.string.layers_title),
            brushSize = stringResource(R.string.brush_size_title),
            renameHint = stringResource(R.string.rename_hint),
            editTextHint = stringResource(R.string.edit_text_hint),
            copyEdits = stringResource(R.string.copy_edits),
            pasteEdits = stringResource(R.string.paste_edits),
            generatePoster = stringResource(R.string.generate_poster),
            duplicate = stringResource(R.string.duplicate),
            unlinkLayer = stringResource(R.string.unlink_layer),
            linkLayer = stringResource(R.string.link_layer),
            hideLayer = stringResource(R.string.hide_layer),
            showLayer = stringResource(R.string.show_layer),
            flattenAll = stringResource(R.string.flatten_all),
            delete = stringResource(R.string.delete),
            lock = stringResource(R.string.lock_button),
            freeze = stringResource(R.string.freeze_button),
            saveProjectHint = stringResource(R.string.save_project_hint)
        ),
        ar = AppStrings.Ar(
            depthUnsupported = stringResource(R.string.depth_unsupported),
            arcoreRequiredTitle = stringResource(R.string.arcore_required_title),
            arcoreRequiredText = stringResource(R.string.arcore_required_text),
            installArcore = stringResource(R.string.install_arcore),
            cameraPermissionRequired = stringResource(R.string.camera_permission_required),
            openSettings = stringResource(R.string.open_settings),
            targetCreationTitle = stringResource(R.string.target_creation_title),
            targetCreationText = stringResource(R.string.target_creation_text),
            diagCopied = stringResource(R.string.diag_copied),
            diagTitle = stringResource(R.string.diag_title),
            diagWaiting = stringResource(R.string.diag_waiting),
            planeConfirmQuestion = stringResource(R.string.plane_confirm_question),
            looksCorrect = stringResource(R.string.looks_correct),
            redetect = stringResource(R.string.redetect),
            planeRealignmentTitle = stringResource(R.string.plane_realignment_title),
            planeRealignmentText = stringResource(R.string.plane_realignment_text),
            useThisWall = stringResource(R.string.use_this_wall),
            scanning = stringResource(R.string.scanning_dots),
            anchorLocked = stringResource(R.string.anchor_locked),
            matchedPercent = { pct -> context.getString(R.string.matched_percent, pct) },
            scanHintRecover = stringResource(R.string.scan_hint_recover),
            scanHintAmbient = { deg -> context.getString(R.string.scan_hint_ambient, deg) },
            scanHintTooDark = stringResource(R.string.scan_hint_too_dark),
            scanHintBuildMap = stringResource(R.string.scan_hint_build_map),
            scanHintCloser = stringResource(R.string.scan_hint_closer),
            scanHintHigherLower = stringResource(R.string.scan_hint_higher_lower)
        ),
        help = AppStrings.Help(
            modeHost = stringResource(R.string.help_mode_host),
            ar = stringResource(R.string.help_ar),
            overlay = stringResource(R.string.help_overlay),
            mockup = stringResource(R.string.help_mockup),
            trace = stringResource(R.string.help_trace),
            targetHost = stringResource(R.string.help_target_host),
            scanModeToggle = stringResource(R.string.help_scan_mode_toggle),
            create = stringResource(R.string.help_create),
            designHost = stringResource(R.string.help_design_host),
            addImg = stringResource(R.string.help_add_img),
            addDraw = stringResource(R.string.help_add_draw),
            addText = stringResource(R.string.help_add_text),
            wall = stringResource(R.string.help_wall),
            projectHost = stringResource(R.string.help_project_host),
            newProject = stringResource(R.string.help_new),
            saveProject = stringResource(R.string.help_save),
            loadProject = stringResource(R.string.help_load),
            exportImage = stringResource(R.string.help_export),
            appSettings = stringResource(R.string.help_settings),
            flashlight = stringResource(R.string.help_light),
            lockTrace = stringResource(R.string.help_lock_trace),
            helpMain = stringResource(R.string.help_help_main),
            layer = { name -> context.getString(R.string.help_layer, name) },
            editText = stringResource(R.string.help_edit_text),
            size = stringResource(R.string.help_size),
            font = stringResource(R.string.help_font),
            color = stringResource(R.string.help_color),
            kern = stringResource(R.string.help_kern),
            bold = stringResource(R.string.help_bold),
            italic = stringResource(R.string.help_italic),
            outline = stringResource(R.string.help_outline),
            shadow = stringResource(R.string.help_shadow),
            stencilGen = stringResource(R.string.help_stencil_gen),
            blend = stringResource(R.string.help_blend),
            adj = stringResource(R.string.help_adj),
            invert = stringResource(R.string.help_invert),
            balance = stringResource(R.string.help_balance),
            eraser = stringResource(R.string.help_eraser),
            blur = stringResource(R.string.help_blur),
            liquify = stringResource(R.string.help_liquify),
            dodge = stringResource(R.string.help_dodge),
            burn = stringResource(R.string.help_burn),
            iso = stringResource(R.string.help_iso),
            line = stringResource(R.string.help_line),
            helpLayer = stringResource(R.string.help_help_layer)
        )
    )
}

data class AppStrings(
    val nav: NavStrings,
    val common: Common,
    val lib: Library,
    val settings: Settings,
    val editor: Editor,
    val ar: Ar,
    val help: Help
) {
    data class Common(
        val cancel: String,
        val done: String,
        val apply: String,
        val close: String,
        val next: String,
        val save: String,
        val retake: String,
        val capture: String,
        val generating: String
    )
    data class Library(
        val title: String,
        val description: String,
        val newProject: String,
        val importProject: String,
        val noProjects: String,
        val noProjectsHint: String,
        val deleteProjectDesc: (String) -> String
    )
    data class Settings(
        val title: String,
        val preferences: String,
        val dominantHand: String,
        val handRight: String,
        val handLeft: String,
        val diagOverlay: String,
        val on: String,
        val off: String,
        val scanMode: String,
        val pointCloud: String,
        val gaussianSplat: String,
        val anchorBoundary: String,
        val units: String,
        val imperial: String,
        val metric: String,
        val canvasBg: String,
        val appInfo: String,
        val version: String,
        val updates: String,
        val checkUpdates: String,
        val installUpdate: String,
        val permissions: String,
        val cameraAccess: String,
        val photoAccess: String,
        val notifications: String,
        val granted: String,
        val denied: String,
        val openAppSettings: String,
        val copyright: String
    )
    data class Editor(
        val layers: String,
        val brushSize: String,
        val renameHint: String,
        val editTextHint: String,
        val copyEdits: String,
        val pasteEdits: String,
        val generatePoster: String,
        val duplicate: String,
        val unlinkLayer: String,
        val linkLayer: String,
        val hideLayer: String,
        val showLayer: String,
        val flattenAll: String,
        val delete: String,
        val lock: String,
        val freeze: String,
        val saveProjectHint: String
    )
    data class Ar(
        val depthUnsupported: String,
        val arcoreRequiredTitle: String,
        val arcoreRequiredText: String,
        val installArcore: String,
        val cameraPermissionRequired: String,
        val openSettings: String,
        val targetCreationTitle: String,
        val targetCreationText: String,
        val diagCopied: String,
        val diagTitle: String,
        val diagWaiting: String,
        val planeConfirmQuestion: String,
        val looksCorrect: String,
        val redetect: String,
        val planeRealignmentTitle: String,
        val planeRealignmentText: String,
        val useThisWall: String,
        val scanning: String,
        val anchorLocked: String,
        val matchedPercent: (Int) -> String,
        val scanHintRecover: String,
        val scanHintAmbient: (Int) -> String,
        val scanHintTooDark: String,
        val scanHintBuildMap: String,
        val scanHintCloser: String,
        val scanHintHigherLower: String
    )
    data class Help(
        val modeHost: String,
        val ar: String,
        val overlay: String,
        val mockup: String,
        val trace: String,
        val targetHost: String,
        val scanModeToggle: String,
        val create: String,
        val designHost: String,
        val addImg: String,
        val addDraw: String,
        val addText: String,
        val wall: String,
        val projectHost: String,
        val newProject: String,
        val saveProject: String,
        val loadProject: String,
        val exportImage: String,
        val appSettings: String,
        val flashlight: String,
        val lockTrace: String,
        val helpMain: String,
        val layer: (String) -> String,
        val editText: String,
        val size: String,
        val font: String,
        val color: String,
        val kern: String,
        val bold: String,
        val italic: String,
        val outline: String,
        val shadow: String,
        val stencilGen: String,
        val blend: String,
        val adj: String,
        val invert: String,
        val balance: String,
        val eraser: String,
        val blur: String,
        val liquify: String,
        val dodge: String,
        val burn: String,
        val iso: String,
        val line: String,
        val helpLayer: String
    )
}
