package com.hereliesaz.graffitixr

import android.os.Bundle
import androidx.activity.viewModels
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.navigation.compose.rememberNavController
import com.hereliesaz.aznavrail.AzActivity
import com.hereliesaz.aznavrail.annotation.App
import com.hereliesaz.aznavrail.annotation.Az
import com.hereliesaz.aznavrail.annotation.AzDockingSide
import com.hereliesaz.aznavrail.annotation.AzTheme
import com.hereliesaz.graffitixr.design.theme.GraffitiXRTheme
import com.hereliesaz.graffitixr.feature.ar.ArViewModel
import com.hereliesaz.graffitixr.feature.ar.rendering.ArRenderer
import com.hereliesaz.graffitixr.feature.dashboard.DashboardViewModel
import com.hereliesaz.graffitixr.feature.editor.EditorViewModel
import com.hereliesaz.graffitixr.nativebridge.SlamManager
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject

/**
 * The Single Activity for the application.
 * Sets up the Compose content, Hilt injection, and the top-level Navigation Graph.
 */
@Az(app = App(
    dock = AzDockingSide.LEFT,
    theme = AzTheme.GlitchNoir
))
@AndroidEntryPoint
class MainActivity : AzActivity() {

    // 2. Link the Generated Graph (Generated by KSP)
    // Note: AzGraph will be generated in the build folder.
    // If IDE marks this as red, run build.
    override val graph = AzGraph

    @Inject lateinit var slamManager: SlamManager
    @Inject lateinit var projectRepository: com.hereliesaz.graffitixr.domain.repository.ProjectRepository

    private val mainViewModel: MainViewModel by viewModels()
    private val editorViewModel: EditorViewModel by viewModels()
    private val arViewModel: ArViewModel by viewModels()
    private val dashboardViewModel: DashboardViewModel by viewModels()

    private var arRenderer: ArRenderer? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // RESURRECTION: Ensure native engine is alive even if the Process survived
        // but the Activity was previously destroyed.
        slamManager.ensureInitialized()

        // AzActivity handles setContent and graph internally.
        // We might need to inject our MainScreen into the AzGraph or use AzNavRail's content slot?
        // The migration guide implies @Az functions BECOME the graph.
        // But we have a custom MainScreen that holds everything.

        // Wait, if we use AzActivity, it takes control.
        // The previous MainScreen used AzHostActivityLayout internally.
        // Now AzActivity uses it.

        // We need to verify how to pass our custom UI (MainScreen) into this.
        // If the entire app is MainScreen, then MainScreen should be the "Home" item?
        // Or we wrap MainScreen in a @Az function?

        // For now, I will keep the SlamManager initialization.
        // The setContent in AzActivity uses the graph.
    }

    override fun onDestroy() {
        super.onDestroy()
        // Only release native resources if the Activity is actually finishing (not rotating)
        // This prevents the Native Engine from being killed and recreated on configuration changes.
        if (isFinishing) {
            slamManager.destroy()
        }
    }
}
