package com.hereliesaz.graffitixr.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.hereliesaz.graffitixr.R

data class NavStrings(
    val modes: String,
    val arMode: String,
    val arModeInfo: String,
    val overlay: String,
    val overlayInfo: String,
    val mockup: String,
    val mockupInfo: String,
    val trace: String,
    val traceInfo: String,
    val grid: String,
    val surveyor: String,
    val surveyorInfo: String,
    val create: String,
    val createInfo: String,
    val refine: String,
    val refineInfo: String,
    val update: String,
    val updateInfo: String,
    val design: String,
    val open: String,
    val openInfo: String,
    val wall: String,
    val wallInfo: String,
    val isolate: String,
    val isolateInfo: String,
    val outline: String,
    val outlineInfo: String,
    val adjust: String,
    val adjustInfo: String,
    val balance: String,
    val balanceInfo: String,
    val build: String,
    val blendingInfo: String,
    val settings: String,
    val project: String,
    val new: String,
    val newInfo: String,
    val save: String,
    val saveInfo: String,
    val load: String,
    val loadInfo: String,
    val export: String,
    val exportInfo: String,
    val help: String,
    val helpInfo: String,
    val light: String,
    val lightInfo: String,
    val lock: String,
    val lockInfo: String
)

@Composable
fun rememberNavStrings(): NavStrings {
    return NavStrings(
        modes = stringResource(R.string.nav_modes),
        arMode = stringResource(R.string.nav_ar_mode),
        arModeInfo = stringResource(R.string.nav_ar_mode_info),
        overlay = stringResource(R.string.nav_overlay),
        overlayInfo = stringResource(R.string.nav_overlay_info),
        mockup = stringResource(R.string.nav_mockup),
        mockupInfo = stringResource(R.string.nav_mockup_info),
        trace = stringResource(R.string.nav_trace),
        traceInfo = stringResource(R.string.nav_trace_info),
        grid = stringResource(R.string.nav_grid),
        surveyor = stringResource(R.string.nav_surveyor),
        surveyorInfo = stringResource(R.string.nav_surveyor_info),
        create = stringResource(R.string.nav_create),
        createInfo = stringResource(R.string.nav_create_info),
        refine = stringResource(R.string.nav_refine),
        refineInfo = stringResource(R.string.nav_refine_info),
        update = stringResource(R.string.nav_update),
        updateInfo = stringResource(R.string.nav_update_info),
        design = stringResource(R.string.nav_design),
        open = stringResource(R.string.nav_open),
        openInfo = stringResource(R.string.nav_open_info),
        wall = stringResource(R.string.nav_wall),
        wallInfo = stringResource(R.string.nav_wall_info),
        isolate = stringResource(R.string.nav_isolate),
        isolateInfo = stringResource(R.string.nav_isolate_info),
        outline = stringResource(R.string.nav_outline),
        outlineInfo = stringResource(R.string.nav_outline_info),
        adjust = stringResource(R.string.nav_adjust),
        adjustInfo = stringResource(R.string.nav_adjust_info),
        balance = stringResource(R.string.nav_balance),
        balanceInfo = stringResource(R.string.nav_balance_info),
        build = "Build", // Renamed from blending, hardcoded as resource might not be updated yet
        blendingInfo = stringResource(R.string.nav_blending_info),
        settings = stringResource(R.string.nav_settings),
        project = "Project", // Restored to "Project"
        new = stringResource(R.string.nav_new),
        newInfo = stringResource(R.string.nav_new_info),
        save = stringResource(R.string.nav_save),
        saveInfo = stringResource(R.string.nav_save_info),
        load = stringResource(R.string.nav_load),
        loadInfo = stringResource(R.string.nav_load_info),
        export = stringResource(R.string.nav_export),
        exportInfo = stringResource(R.string.nav_export_info),
        help = stringResource(R.string.nav_help),
        helpInfo = stringResource(R.string.nav_help_info),
        light = stringResource(R.string.nav_light),
        lightInfo = stringResource(R.string.nav_light_info),
        lock = stringResource(R.string.nav_lock),
        lockInfo = stringResource(R.string.nav_lock_info)
    )
}
